document.addEventListener('DOMContentLoaded', () => {
    // Get references to DOM elements
    const startDateInput = document.getElementById('start-date');
    const intervalSelect = document.getElementById('watering-interval');
    const durationButtons = document.querySelectorAll('.duration-btn');
    const scheduleList = document.getElementById('schedule-list');
    const exportBtn = document.getElementById('export-calendar-btn');

    // --- Initial Setup ---

    // Populate the interval dropdown with options from 1 to 100
    for (let i = 1; i <= 100; i++) {
        const option = document.createElement('option');
        option.value = i;
        option.textContent = i;
        if (i === 7) {
            option.selected = true; // Set 7 as the default
        }
        intervalSelect.appendChild(option);
    }

    // Set default start date to today
    const today = new Date();
    startDateInput.value = today.toISOString().split('T')[0];

    let wateringEvents = [];

    // --- Core Functions ---

    // Function to calculate watering dates
    const calculateSchedule = () => {
        const startDate = new Date(startDateInput.value + 'T00:00:00'); // Use T00:00:00 to prevent timezone issues
        const interval = parseInt(intervalSelect.value, 10);
        const activeDurationBtn = document.querySelector('.duration-btn.active');
        const months = parseInt(activeDurationBtn.dataset.months, 10);

        if (isNaN(startDate.getTime()) || isNaN(interval) || interval <= 0) {
            scheduleList.innerHTML = '<p class="placeholder">Please select a valid start date and interval.</p>';
            exportBtn.disabled = true;
            return;
        }

        wateringEvents = [];
        const schedule = [];
        const endDate = new Date(startDate);
        endDate.setMonth(endDate.getMonth() + months);

        let currentDate = new Date(startDate);

        while (currentDate <= endDate) {
            schedule.push(new Date(currentDate));
            wateringEvents.push({
                title: 'Water Your Plants',
                startDate: new Date(currentDate)
            });
            currentDate.setDate(currentDate.getDate() + interval);
        }

        displaySchedule(schedule);
        exportBtn.disabled = schedule.length === 0;
    };

    // Function to display the schedule, ensuring dates are in English
    const displaySchedule = (schedule) => {
        scheduleList.innerHTML = ''; // Clear previous results
        if (schedule.length === 0) {
            scheduleList.innerHTML = '<p class="placeholder">No watering dates in this period.</p>'
            return;
        }

        schedule.forEach(date => {
            const item = document.createElement('div');
            item.className = 'schedule-item';
            // Force English (US) format for the date
            item.textContent = date.toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' });
            scheduleList.appendChild(item);
        });
    };

    // Function to generate and download an iCalendar (.ics) file
    const exportToCalendar = () => {
        if (wateringEvents.length === 0) return;

        let icsContent = [
            'BEGIN:VCALENDAR',
            'VERSION:2.0',
            'PRODID:-//flwllxkal-eng/myproject1//NONSGML v1.0//EN'
        ];

        wateringEvents.forEach(event => {
            const eventDate = event.startDate;
            const year = eventDate.getFullYear();
            const month = ('0' + (eventDate.getMonth() + 1)).slice(-2);
            const day = ('0' + eventDate.getDate()).slice(-2);
            const dateString = `${year}${month}${day}`;

            icsContent.push(
                'BEGIN:VEVENT',
                `DTSTAMP:${dateString}T000000Z`,
                `DTSTART;VALUE=DATE:${dateString}`,
                `SUMMARY:${event.title}`,
                'DESCRIPTION:Time to water your plants! Generated by Plant Watering Scheduler.',
                'END:VEVENT'
            );
        });

        icsContent.push('END:VCALENDAR');
        const icsFile = icsContent.join('\r\n');

        const blob = new Blob([icsFile], { type: 'text/calendar;charset=utf-8' });
        const link = document.createElement('a');
        link.href = URL.createObjectURL(blob);
        link.download = 'plant_watering_schedule.ics';
        document.body.appendChild(link); // Required for Firefox
        link.click();
        document.body.removeChild(link);
    };

    // --- Event Listeners ---

    startDateInput.addEventListener('change', calculateSchedule);
    intervalSelect.addEventListener('change', calculateSchedule);

    durationButtons.forEach(button => {
        button.addEventListener('click', () => {
            durationButtons.forEach(btn => btn.classList.remove('active'));
            button.classList.add('active');
            calculateSchedule();
        });
    });

    exportBtn.addEventListener('click', exportToCalendar);

    // --- Initial Calculation ---

    // Calculate the schedule on page load with the default values
    calculateSchedule();
});
